languages:
  JavaScript: true
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_fingerprints:
    - 5739ed17d29c37f0a33caabbac61dedf
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- test/
- "**.spec.js"
- webpack.config.js
